FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o full-cycle-rocks

FROM scratch

COPY --from=builder /app/full-cycle-rocks /

ENTRYPOINT ["/full-cycle-rocks"]
